# 1. URL de la Base de Datos (Localhost y el puerto de MySQL por defecto)
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_biblioteca_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# 2. Credenciales de tu MySQL local
spring.datasource.username=root
spring.datasource.password=qwerty00

# 3. Driver de conexión
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# 5. Para ver en la consola de IntelliJ las consultas SQL que hace Spring (Muy útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true